import type { VideoSource } from '@/lib/types';

/**
 * Default predefined video sources - Comprehensive CMS API database
 * Sources are based on well-known Chinese video aggregation platforms
 * 
 * Standard CMS API format:
 *   baseUrl: domain/api.php/provide/vod/
 *   searchPath: ?ac=videolist&wd={keyword}&pg={page}
 *   detailPath: ?ac=detail&ids={id}
 */
export const DEFAULT_SOURCES: VideoSource[] = [
  // ====== 一级资源站 (High Priority CMS APIs) ======
  {
    id: 'bfzyapi',
    name: '暴风资源',
    baseUrl: 'https://bfzyapi.com/api.php/provide/vod/',
    searchPath: '/?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '/?ac=detail&ids={id}',
    priority: 1,
    group: 'normal',
    enabled: true,
  },
  {
    id: 'suoniapi',
    name: '索尼资源',
    baseUrl: 'https://suoniapi.com/api.php/provide/vod/',
    searchPath: '/?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '/?ac=detail&ids={id}',
    priority: 2,
    group: 'normal',
    enabled: true,
  },
  {
    id: 'lziapi',
    name: '量子资源',
    baseUrl: 'https://cj.lziapi.com/api.php/provide/vod/',
    searchPath: '/?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '/?ac=detail&ids={id}',
    priority: 3,
    group: 'normal',
    enabled: true,
  },
  {
    id: 'feisuzy',
    name: '飞速资源',
    baseUrl: 'https://www.feisuzyapi.com/api.php/provide/vod/',
    searchPath: '/?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '/?ac=detail&ids={id}',
    priority: 4,
    group: 'normal',
    enabled: true,
  },
  {
    id: 'ffzyapi',
    name: '非凡资源',
    baseUrl: 'http://cj.ffzyapi.com/api.php/provide/vod/',
    searchPath: '/?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '/?ac=detail&ids={id}',
    priority: 5,
    group: 'normal',
    enabled: true,
  },
  {
    id: 'haiwaikan',
    name: '海外看',
    baseUrl: 'https://haiwaikan.com/api.php/provide/vod/',
    searchPath: '/?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '/?ac=detail&ids={id}',
    priority: 6,
    group: 'normal',
    enabled: true,
  },
  {
    id: 'kuaifan',
    name: '快帆资源',
    baseUrl: 'https://api.kuaifan.tv/api.php/provide/vod/',
    searchPath: '/?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '/?ac=detail&ids={id}',
    priority: 7,
    group: 'normal',
    enabled: true,
  },
  {
    id: 'lzizy',
    name: '量子资源站',
    baseUrl: 'https://lzizy1.com/api.php/provide/vod/',
    searchPath: '/?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '/?ac=detail&ids={id}',
    priority: 8,
    group: 'normal',
    enabled: true,
  },
  {
    id: '49zy',
    name: '四九资源',
    baseUrl: 'https://49zy1.com/api.php/provide/vod/',
    searchPath: '/?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '/?ac=detail&ids={id}',
    priority: 9,
    group: 'normal',
    enabled: true,
  },
  {
    id: 'qhzyapi',
    name: '奇虎资源',
    baseUrl: 'https://caiji.qhzyapi.com/api.php/provide/vod/',
    searchPath: '/?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '/?ac=detail&ids={id}',
    priority: 10,
    group: 'normal',
    enabled: true,
  },
  {
    id: 'kekezy',
    name: '可可资源',
    baseUrl: 'https://kekezy1.com/api.php/provide/vod/',
    searchPath: '/?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '/?ac=detail&ids={id}',
    priority: 11,
    group: 'normal',
    enabled: true,
  },
  {
    id: 'huyaapi',
    name: '虎牙采集',
    baseUrl: 'https://www.huyaapi.com/api.php/provide/vod/',
    searchPath: '/?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '/?ac=detail&ids={id}',
    priority: 12,
    group: 'normal',
    enabled: true,
  },
  {
    id: 'hhzyapi',
    name: '火狐采集',
    baseUrl: 'https://hhzyapi.com/api.php/provide/vod/',
    searchPath: '/?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '/?ac=detail&ids={id}',
    priority: 13,
    group: 'normal',
    enabled: true,
  },
  {
    id: 'apibdzy',
    name: '百度资源',
    baseUrl: 'https://api.apibdzy.com/api.php/provide/vod/',
    searchPath: '/?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '/?ac=detail&ids={id}',
    priority: 14,
    group: 'normal',
    enabled: true,
  },
  {
    id: 'taopian',
    name: '淘片资源',
    baseUrl: 'https://taopianapi.com/cjapi/mc/vod/json.html',
    searchPath: '?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '?ac=detail&ids={id}',
    priority: 15,
    group: 'normal',
    enabled: true,
  },
  {
    id: 'app_bfzy',
    name: '暴风影音',
    baseUrl: 'https://app.bfzyapi.com/api.php/provide/vod/',
    searchPath: '/?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '/?ac=detail&ids={id}',
    priority: 16,
    group: 'normal',
    enabled: true,
  },

  // ====== 推荐资源站 (Additional CMS APIs) ======
  {
    id: 'wolongzy',
    name: '卧龙资源',
    baseUrl: 'https://wolongzy.com/api.php/provide/vod/',
    searchPath: '/?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '/?ac=detail&ids={id}',
    priority: 20,
    group: 'normal',
    enabled: true,
  },
  {
    id: 'jinyingzy',
    name: '金鹰资源',
    baseUrl: 'https://jinyingzy.com/api.php/provide/vod/',
    searchPath: '/?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '/?ac=detail&ids={id}',
    priority: 21,
    group: 'normal',
    enabled: true,
  },
  {
    id: 'yinghuazy',
    name: '樱花资源',
    baseUrl: 'https://yinghuazy.com/api.php/provide/vod/',
    searchPath: '/?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '/?ac=detail&ids={id}',
    priority: 22,
    group: 'normal',
    enabled: true,
  },
  {
    id: 'haohuazy',
    name: '豪华资源',
    baseUrl: 'https://haohuazy.com/api.php/provide/vod/',
    searchPath: '/?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '/?ac=detail&ids={id}',
    priority: 23,
    group: 'normal',
    enabled: true,
  },
  {
    id: 'kuaichezy',
    name: '快车资源',
    baseUrl: 'https://kuaichezy.com/api.php/provide/vod/',
    searchPath: '/?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '/?ac=detail&ids={id}',
    priority: 24,
    group: 'normal',
    enabled: true,
  },
  {
    id: 'jisuzuida',
    name: '极速资源',
    baseUrl: 'https://jisuzuida.com/api.php/provide/vod/',
    searchPath: '/?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '/?ac=detail&ids={id}',
    priority: 25,
    group: 'normal',
    enabled: true,
  },
  {
    id: 'wuqiongzy',
    name: '无穷资源',
    baseUrl: 'https://wuqiongzy.com/api.php/provide/vod/',
    searchPath: '/?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '/?ac=detail&ids={id}',
    priority: 26,
    group: 'normal',
    enabled: true,
  },
  {
    id: 'hongniuzy',
    name: '红牛资源',
    baseUrl: 'https://hongniuzy.com/api.php/provide/vod/',
    searchPath: '/?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '/?ac=detail&ids={id}',
    priority: 27,
    group: 'normal',
    enabled: true,
  },
  {
    id: 'shandianzy',
    name: '闪电资源',
    baseUrl: 'https://shandianzy.com/api.php/provide/vod/',
    searchPath: '/?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '/?ac=detail&ids={id}',
    priority: 28,
    group: 'normal',
    enabled: true,
  },
  {
    id: 'leshiapi',
    name: '乐视资源',
    baseUrl: 'https://leshiapi.com/api.php/provide/vod/',
    searchPath: '/?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '/?ac=detail&ids={id}',
    priority: 29,
    group: 'normal',
    enabled: true,
  },
  {
    id: 'xiandaiapi',
    name: '现代资源',
    baseUrl: 'https://xiandaiapi.com/api.php/provide/vod/',
    searchPath: '/?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '/?ac=detail&ids={id}',
    priority: 30,
    group: 'normal',
    enabled: true,
  },
  {
    id: 'languangzy',
    name: '蓝光资源',
    baseUrl: 'https://languangzy.com/api.php/provide/vod/',
    searchPath: '/?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '/?ac=detail&ids={id}',
    priority: 31,
    group: 'normal',
    enabled: true,
  },
  {
    id: 'xinlangzy',
    name: '新浪采集',
    baseUrl: 'https://xinlangzy.com/api.php/provide/vod/',
    searchPath: '/?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '/?ac=detail&ids={id}',
    priority: 32,
    group: 'normal',
    enabled: true,
  },
  {
    id: 'tiankongzy',
    name: '天空资源',
    baseUrl: 'https://tiankongzy.com/api.php/provide/vod/',
    searchPath: '/?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '/?ac=detail&ids={id}',
    priority: 33,
    group: 'normal',
    enabled: true,
  },
  {
    id: 'baiduziuan',
    name: '百度资源站',
    baseUrl: 'https://baiduziuan.com/api.php/provide/vod/',
    searchPath: '/?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '/?ac=detail&ids={id}',
    priority: 34,
    group: 'normal',
    enabled: true,
  },
  // 小胡资源 - popular Chinese TV source
  {
    id: 'xiaohu',
    name: '小胡资源',
    baseUrl: 'https://c.xiaohu.icu/api.php/provide/vod/',
    searchPath: '/?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '/?ac=detail&ids={id}',
    priority: 35,
    group: 'normal',
    enabled: true,
  },
  // MV资源
  {
    id: 'mv_wogg',
    name: 'MV音乐',
    baseUrl: 'https://mv.wogg.link/mv/vod',
    searchPath: '?ac=videolist&wd={keyword}&pg={page}',
    detailPath: '?ac=detail&ids={id}',
    priority: 36,
    group: 'normal',
    enabled: true,
  },
];

// Export the subscription source URLs for external import
export const SUBSCRIPTION_SOURCES = [
  {
    name: '饭太硬源',
    url: 'http://mdyso.cn',
    note: '老牌稳定，线路极快',
  },
  {
    name: '肥猫源',
    url: 'http://feedata.cf',
    note: '更新频繁，分类极细',
  },
  {
    name: '开心源',
    url: 'http://kaitv.cn',
    note: '主打高清、无广告秒播',
  },
  {
    name: '骚零源',
    url: 'https://100km.top',
    note: '备用首选，源站丰富',
  },
  {
    name: '唐三源',
    url: 'https://ghproxy.com',
    note: '代理加速源',
  },
  {
    name: '巧儿源',
    url: 'http://miaogongzi.net',
    note: '优质采集源',
  },
  {
    name: '菜妮丝源',
    url: 'https://cainis.top',
    note: '分类齐全',
  },
  {
    name: '嗷呜源',
    url: 'https://liucn.cc',
    note: '稳定可靠',
  },
  {
    name: '荷城茶秀',
    url: 'http://hechengchaxiu.com',
    note: '综合影视源',
  },
  {
    name: '小雅Alisund源',
    url: 'http://drpy.site',
    note: '主打阿里网盘超清原盘资源',
  },
  // Additional well-known subscription sources
  {
    name: '高天流云0827',
    url: 'https://fastly.jsdelivr.net/gh/gaotianliuyun/gao@master/0827.json',
    note: '经典多源聚合',
  },
  {
    name: '聚玩盒子4K',
    url: 'http://xhztv.top/4k.json',
    note: '4K超清专源',
  },
  {
    name: 'XYQTVBox',
    url: 'https://fastly.jsdelivr.net/gh/xyq254245/xyqonlinerule@main/XYQTVBox.json',
    note: '多源聚合',
  },
  {
    name: 'liu673cn',
    url: 'https://fastly.jsdelivr.net/gh/liu673cn/box@main/m.json',
    note: '知名聚合源',
  },
  {
    name: '蜗牛源',
    url: 'https://tv.蜗牛.top/DC.txt',
    note: '稳定聚合源',
  },
  {
    name: 'duomv源',
    url: 'https://gitlab.com/duomv/dzhipy/-/raw/main/index.json',
    note: '音乐MV专源',
  },
];

// Export the standalone video websites (for reference - not CMS API compatible)
export const STREAMING_SITES = [
  { name: '低端影视', url: 'https://ddys.pro', note: '主打大码率超清美剧、电影，画质天花板' },
  { name: '厂长资源', url: 'https://czzy.top', note: '更新速度极快，独家高画质海外影视' },
  { name: '在线之家', url: 'https://zxzj.pro', note: '主打超清美剧、韩剧、日剧' },
  { name: 'AGE动漫', url: 'https://agedm.org', note: '全网最全的动漫视频源' },
  { name: '哔嘀影视', url: 'https://bde4.icu', note: '4K/1080P 高清影视流媒体源' },
  { name: '4K影视站', url: 'https://4kyingshi.com', note: '专门提供 4K HDR 极佳画质音效源' },
  { name: '胖子视频', url: 'https://pangzi.com', note: '经典海外高分影视资源' },
  { name: '欧乐影院', url: 'https://olevod.com', note: '适合海外华人的极速影视源' },
  { name: '独播库', url: 'https://duboku.tv', note: '电视剧无延迟、免会员直连' },
  { name: '看剧网', url: 'https://kanju.com', note: '聚合全网独播剧' },
  { name: '奈飞工厂', url: 'https://netflixgc.com', note: '还原奈飞高画质的免费影视站' },
  { name: '天天美剧', url: 'https://ttmj.tv', note: '资深美剧迷必备的底层源' },
  { name: '二次元动漫', url: 'https://animetv.net', note: '纯净无弹窗动漫源' },
  { name: '真不卡影院', url: 'https://zhenbuka.com', note: '主打加载速度，服务器带宽极大' },
  { name: '茶杯狐', url: 'https://chabaifu.com', note: '影视资源搜索引擎源头' },
];

// Export cloud drive search sites (for reference)
export const CLOUD_DRIVE_SITES = [
  { name: '阿里盘搜', url: 'https://alipansou.com' },
  { name: '盘小站', url: 'https://panxz.com' },
  { name: '猫狸盘搜', url: 'https://maolipanso.com' },
  { name: '易搜', url: 'https://yiso.fun' },
  { name: '阡陌搜', url: 'https://qianmosou.com' },
  { name: '夸克搜', url: 'https://kuakesou.com' },
  { name: '趣盘搜', url: 'https://qupanso.com' },
  { name: '聚盘搜索', url: 'https://jupanso.com' },
  { name: '盘多多', url: 'https://pandodo.com' },
  { name: '搜盘哦', url: 'https://soupan-oh.com' },
  { name: '影音盘', url: 'https://yingyinjuhui.com' },
  { name: '达达搜', url: 'https://dadasou.com' },
  { name: '4K原盘分享站', url: 'https://4kyp.com' },
  { name: '天翼云分享基地', url: 'https://cloud189.com' },
];
